import type { Settings, Strategy, Trade } from './types';

const CREATED_AT = '2026-08-08T08:00:00.000Z';

export const DEMO_SETTINGS: Settings = {
  id: 'demo-settings',
  starting_balance: 10000,
  pip_size: 0.01,
  pip_value_per_lot: 1,
  risk_warning_threshold: 2,
  idle_timeout_minutes: 30,
  updated_at: CREATED_AT,
};

export const DEMO_STRATEGIES: Strategy[] = [
  'Breakout',
  'Reversal',
  'Trend Following',
  'Scalp',
  'News Play',
].map((name, index) => ({
  id: `demo-strategy-${index + 1}`,
  name,
  created_at: CREATED_AT,
}));

const goldTrades: Array<Omit<Trade, 'id' | 'created_at' | 'updated_at'>> = [
  {
    trade_number: 1,
    date: '2026-07-14',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'Breakout',
    calc_mode: 'pips',
    entry_price: 3318.4,
    exit_price: 3331.8,
    lot_size: 0.1,
    fees: 3.5,
    stop_loss: 3310.4,
    target_price: 3334.4,
    setup_notes: 'London range breakout with a retest above resistance.',
    lessons_learned: 'Waiting for the retest avoided the first false break.',
  },
  {
    trade_number: 2,
    date: '2026-07-16',
    symbol: 'XAUUSD',
    direction: 'Short',
    strategy: 'Reversal',
    calc_mode: 'pips',
    entry_price: 3342.7,
    exit_price: 3336.2,
    lot_size: 0.12,
    fees: 3.8,
    stop_loss: 3349.2,
    target_price: 3330.0,
    setup_notes: 'Rejection wick at prior daily resistance.',
    lessons_learned: 'Partial profit near intraday support would reduce volatility.',
  },
  {
    trade_number: 3,
    date: '2026-07-18',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'Trend Following',
    calc_mode: 'pips',
    entry_price: 3329.1,
    exit_price: 3323.6,
    lot_size: 0.1,
    fees: 3.2,
    stop_loss: 3322.1,
    target_price: 3343.1,
    setup_notes: 'Pullback entry in an hourly uptrend.',
    lessons_learned: 'The higher-low structure had already failed before entry.',
  },
  {
    trade_number: 4,
    date: '2026-07-22',
    symbol: 'XAUUSD',
    direction: 'Short',
    strategy: 'News Play',
    calc_mode: 'pips',
    entry_price: 3361.5,
    exit_price: 3345.9,
    lot_size: 0.08,
    fees: 4.1,
    stop_loss: 3371.5,
    target_price: 3341.5,
    setup_notes: 'Post-news momentum after the first five-minute candle closed.',
    lessons_learned: 'Reduced size kept risk controlled during wider spreads.',
  },
  {
    trade_number: 5,
    date: '2026-07-25',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'Scalp',
    calc_mode: 'pips',
    entry_price: 3350.2,
    exit_price: 3354.6,
    lot_size: 0.15,
    fees: 4.5,
    stop_loss: 3346.2,
    target_price: 3356.2,
    setup_notes: 'New York open sweep and quick reclaim.',
    lessons_learned: 'The planned short holding period matched the setup.',
  },
  {
    trade_number: 6,
    date: '2026-07-29',
    symbol: 'XAUUSD',
    direction: 'Short',
    strategy: 'Breakout',
    calc_mode: 'pips',
    entry_price: 3377.8,
    exit_price: 3384.1,
    lot_size: 0.1,
    fees: 3.4,
    stop_loss: 3385.8,
    target_price: 3361.8,
    setup_notes: 'Attempted breakdown below the Asian session low.',
    lessons_learned: 'Avoid entering when the breakout candle closes back in range.',
  },
  {
    trade_number: 7,
    date: '2026-08-01',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'Reversal',
    calc_mode: 'pips',
    entry_price: 3368.6,
    exit_price: 3382.3,
    lot_size: 0.1,
    fees: 3.6,
    stop_loss: 3359.6,
    target_price: 3386.6,
    setup_notes: 'Bullish divergence and reclaim of the prior day low.',
    lessons_learned: 'Confluence supported holding beyond the first resistance.',
  },
  {
    trade_number: 8,
    date: '2026-08-03',
    symbol: 'XAUUSD',
    direction: 'Short',
    strategy: 'Scalp',
    calc_mode: 'pips',
    entry_price: 3391.4,
    exit_price: 3387.0,
    lot_size: 0.15,
    fees: 4.4,
    stop_loss: 3395.4,
    target_price: 3385.4,
    setup_notes: 'Liquidity sweep above the morning high.',
    lessons_learned: 'Fast execution was important as momentum faded quickly.',
  },
  {
    trade_number: 9,
    date: '2026-08-04',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'Trend Following',
    calc_mode: 'pips',
    entry_price: 3385.2,
    exit_price: 3396.9,
    lot_size: 0.1,
    fees: 3.5,
    stop_loss: 3377.2,
    target_price: 3401.2,
    setup_notes: 'Higher-low continuation after an hourly consolidation.',
    lessons_learned: 'Trailing below the last fifteen-minute swing protected profit.',
  },
  {
    trade_number: 10,
    date: '2026-08-05',
    symbol: 'XAUUSD',
    direction: 'Short',
    strategy: 'Reversal',
    calc_mode: 'pips',
    entry_price: 3404.8,
    exit_price: 3408.9,
    lot_size: 0.12,
    fees: 3.8,
    stop_loss: 3410.8,
    target_price: 3392.8,
    setup_notes: 'Early fade against a strong bullish session.',
    lessons_learned: 'Do not anticipate reversal confirmation in strong momentum.',
  },
  {
    trade_number: 11,
    date: '2026-08-06',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'News Play',
    calc_mode: 'pips',
    entry_price: 3412.3,
    exit_price: 3428.7,
    lot_size: 0.08,
    fees: 4.2,
    stop_loss: 3402.3,
    target_price: 3432.3,
    setup_notes: 'Continuation after volatility compressed following the release.',
    lessons_learned: 'Small size made it easier to follow the original target.',
  },
  {
    trade_number: 12,
    date: '2026-08-08',
    symbol: 'XAUUSD',
    direction: 'Long',
    strategy: 'Breakout',
    calc_mode: 'pips',
    entry_price: 3422.6,
    exit_price: 3430.2,
    lot_size: 0.1,
    fees: 3.5,
    stop_loss: 3415.6,
    target_price: 3436.6,
    setup_notes: 'Break and retest of the weekly high.',
    lessons_learned: 'Good execution; keep waiting for confirmation before entry.',
  },
];

export const DEMO_TRADES: Trade[] = goldTrades.map((trade, index) => ({
  ...trade,
  id: `demo-trade-${index + 1}`,
  created_at: CREATED_AT,
  updated_at: CREATED_AT,
}));
