"use client";

import { LoadingState, StatusBadge } from "@/components/ui/portal-ui";
import { api } from "@/lib/api";
import { statusLabel } from "@/lib/formatters";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Profile = Record<string, unknown> & { id: number; name: string; code: string; application_reference: string; portal_status: string; compliance_status: string; categories: { id: number; name: string }[] };
const fields = [
  ["Legal name", "legal_name"], ["Trading name", "trading_name"], ["Supplier code", "code"], ["Application reference", "application_reference"], ["Supplier type", "supplier_type"], ["Registration number", "registration_number"], ["BRELA number", "brela_registration_number"], ["TIN", "tin_number"], ["VAT number", "vat_registration_number"], ["Business licence", "business_license_number"], ["Business licence expiry", "business_license_expiry_date"], ["Tax clearance", "tax_clearance_number"], ["Tax clearance expiry", "tax_clearance_expiry_date"], ["Primary contact", "primary_contact_name"], ["Position", "primary_contact_position"], ["Contact email", "primary_contact_email"], ["Phone", "primary_contact_phone"], ["Office address", "physical_office_address"], ["Ward", "ward"], ["District", "district"], ["Region", "region"], ["Country", "country"], ["Products and services", "products_services"], ["Delivery coverage", "delivery_coverage_areas"],
] as const;
const editable = ["trading_name", "physical_office_address", "building_plot_street", "ward", "district", "region", "country", "postal_address", "website", "primary_contact_name", "primary_contact_position", "primary_contact_phone", "primary_contact_email", "alternate_contact_name", "alternate_contact_phone", "products_services", "manufacturer_or_distributor_status", "years_in_operation", "delivery_coverage_areas", "quality_management_notes"];

export function SupplierProfile() {
  const [profile, setProfile] = useState<Profile | null>(null); const [editing, setEditing] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(() => api<{ data: Profile }>("supplier-portal/profile").then((value) => setProfile(value.data)), []);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; const raw = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await api("supplier-portal/profile", { method: "PATCH", body: JSON.stringify({ ...raw, regulated_supplier: profile.regulated_supplier ?? false, category_ids: profile.categories.map((category) => category.id) }) }); setMessage("Profile changes submitted for compliance review."); setEditing(false); await load(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Profile update failed."); } }
  if (!profile) return <LoadingState />;
  return <div className="supplier-page"><header className="supplier-page-heading"><div><span className="eyebrow">Supplier record</span><h1>Company profile</h1><p>Your business identity, operational capability, and current compliance request.</p></div><div className="supplier-heading-status"><StatusBadge status={profile.portal_status} /><StatusBadge status={profile.compliance_status ?? "incomplete"} /></div></header>{message && <div className="portal-alert">{message}</div>}<section className="supplier-panel"><div className="panel-heading"><div><h2>Registered details</h2><p>Changes to an approved profile return it to verification.</p></div><button className="portal-button secondary" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Update profile"}</button></div>{editing ? <form className="portal-form-grid two" onSubmit={save}>{editable.map((name) => <label className={`portal-field ${["physical_office_address", "products_services", "delivery_coverage_areas", "quality_management_notes"].includes(name) ? "full" : ""}`} key={name}><span>{statusLabel(name)}</span>{["physical_office_address", "products_services", "delivery_coverage_areas", "quality_management_notes"].includes(name) ? <textarea name={name} defaultValue={String(profile[name] ?? "")} required={["physical_office_address", "products_services"].includes(name)} /> : <input name={name} type={name === "primary_contact_email" ? "email" : name === "years_in_operation" ? "number" : "text"} defaultValue={String(profile[name] ?? "")} required={["region", "country", "primary_contact_name", "primary_contact_phone", "primary_contact_email"].includes(name)} />}</label>)}<button className="portal-button primary">Submit changes</button></form> : <div className="profile-details">{fields.map(([label, key]) => <div key={key}><span>{label}</span><strong>{profile[key] ? String(profile[key]) : "—"}</strong></div>)}</div>}</section><section className="supplier-panel"><h2>Approved categories</h2><div className="category-tags">{profile.categories.map((category) => <span key={category.id}>{category.name}</span>)}</div>{profile.portal_status === "requires_correction" && <div className="portal-alert warning">Profile changes requested: {String(profile.review_comments ?? "Review your company details and documents.")}</div>}</section></div>;
}
