"use client";

import { FieldError } from "@/components/ui/portal-ui";
import { api, ApiError } from "@/lib/api";
import type { Category } from "@/lib/portal-types";
import { Building2, Check, ChevronLeft, ChevronRight, LoaderCircle, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Values = Record<string, string | boolean | number[]>;
const initial: Values = { email: "", password: "", password_confirmation: "", legal_name: "", trading_name: "", registration_number: "", tin_number: "", vat_number: "", supplier_type: "company", address: "", region: "", country: "Tanzania", website: "", contact_name: "", contact_position: "", phone: "", alternate_phone: "", category_ids: [], products_services: "", manufacturer_details: "", declaration_accurate: false, agree_terms: false, agree_privacy: false };

export function SupplierRegistrationForm() {
  const router = useRouter(); const [step, setStep] = useState(1); const [values, setValues] = useState<Values>(initial); const [categories, setCategories] = useState<Category[]>([]); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { void api<{ data: Category[] }>("portal/supplier-categories").then((data) => setCategories(data.data)); }, []);
  const set = (name: string, value: string | boolean | number[]) => setValues((current) => ({ ...current, [name]: value }));
  function toggleCategory(id: number) { const ids = values.category_ids as number[]; set("category_ids", ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]); }
  async function submit(event: FormEvent) { event.preventDefault(); if (step < 4) { setStep(step + 1); return; } setSubmitting(true); setErrors({}); try { const result = await api<{ data: { application_reference: string } }>("portal/supplier-registration", { method: "POST", body: JSON.stringify(values) }); router.push(`/supplier-registration/success?reference=${encodeURIComponent(result.data.application_reference)}`); } catch (caught) { if (caught instanceof ApiError) setErrors(caught.errors ?? { form: [caught.message] }); } finally { setSubmitting(false); } }
  const input = (name: string, label: string, type = "text", required = true) => <label className="portal-field"><span>{label}{required && " *"}</span><input type={type} value={String(values[name])} onChange={(e) => set(name, e.target.value)} required={required} /><FieldError message={errors[name]?.[0]} /></label>;
  return <div className="registration-shell"><ol className="stepper">{([[1, "Account"], [2, "Company"], [3, "Contact & categories"], [4, "Declaration"]] as const).map(([number, label]) => <li className={step >= number ? "active" : ""} key={number}><span>{step > number ? <Check size={15} /> : number}</span><strong>{label}</strong></li>)}</ol>
    <form className="registration-form" onSubmit={submit}><header><span className="eyebrow">Step {step} of 4</span><h1>{step === 1 ? "Create your supplier account" : step === 2 ? "Tell us about your company" : step === 3 ? "Contacts and capabilities" : "Review and declare"}</h1><p>Fields marked with an asterisk are required.</p></header>
      {errors.form && <div className="portal-alert error">{errors.form[0]}</div>}
      {step === 1 && <div className="portal-form-grid"><div className="form-callout"><UserRound size={22} /><p>Use a company-controlled email address. It will become the login for this supplier account.</p></div>{input("email", "Company email", "email")}{input("password", "Password", "password")}{input("password_confirmation", "Confirm password", "password")}</div>}
      {step === 2 && <div className="portal-form-grid two"><div className="form-callout full"><Building2 size={22} /><p>Enter details exactly as they appear on official registration and tax documents.</p></div>{input("legal_name", "Legal name")}{input("trading_name", "Trading name", "text", false)}{input("registration_number", "Company registration number")}{input("tin_number", "TIN number")}{input("vat_number", "VAT number", "text", false)}<label className="portal-field"><span>Supplier type *</span><select value={String(values.supplier_type)} onChange={(e) => set("supplier_type", e.target.value)}><option value="company">Company</option><option value="sole_trader">Sole trader</option><option value="manufacturer">Manufacturer</option><option value="distributor">Distributor</option><option value="consultant">Consultant</option></select></label><label className="portal-field full"><span>Physical address *</span><textarea value={String(values.address)} onChange={(e) => set("address", e.target.value)} required /></label>{input("region", "Region")}{input("country", "Country")}{input("website", "Website", "url", false)}</div>}
      {step === 3 && <div className="portal-form-grid two">{input("contact_name", "Primary contact name")}{input("contact_position", "Position")}{input("phone", "Phone", "tel")}{input("alternate_phone", "Alternate phone", "tel", false)}<fieldset className="category-picker full"><legend>Supplier categories *</legend>{categories.map((category) => <label key={category.id}><input type="checkbox" checked={(values.category_ids as number[]).includes(category.id)} onChange={() => toggleCategory(category.id)} /><span>{category.name}</span></label>)}<FieldError message={errors.category_ids?.[0]} /></fieldset><label className="portal-field full"><span>Products and services offered *</span><textarea value={String(values.products_services)} onChange={(e) => set("products_services", e.target.value)} required /></label><label className="portal-field full"><span>Manufacturer or distributor details</span><textarea value={String(values.manufacturer_details)} onChange={(e) => set("manufacturer_details", e.target.value)} /></label></div>}
      {step === 4 && <div className="declaration"><div className="application-summary"><h2>{String(values.legal_name)}</h2><p>{String(values.email)} · {String(values.region)}, {String(values.country)}</p><span>{(values.category_ids as number[]).length} supplier categor{(values.category_ids as number[]).length === 1 ? "y" : "ies"}</span></div>{[["declaration_accurate", "I confirm that the submitted information is complete and accurate."], ["agree_terms", "I agree to the procurement portal terms and conditions."], ["agree_privacy", "I agree to the privacy notice and authorised document review."]].map(([name, label]) => <label className="declaration-check" key={name}><input type="checkbox" checked={Boolean(values[name])} onChange={(e) => set(name, e.target.checked)} required /><span>{label}</span></label>)}</div>}
      <footer><button type="button" className="portal-button secondary" disabled={step === 1 || submitting} onClick={() => setStep(step - 1)}><ChevronLeft size={17} /> Back</button><button className="portal-button primary" disabled={submitting}>{submitting ? <LoaderCircle className="spin" size={17} /> : step < 4 ? <ChevronRight size={17} /> : <Check size={17} />}{submitting ? "Submitting" : step < 4 ? "Continue" : "Submit application"}</button></footer>
    </form>
  </div>;
}
