"use client";
import { EmptyState, LoadingState, StatusBadge } from "@/components/ui/portal-ui";
import { api } from "@/lib/api";
import { AlertTriangle, CheckCircle2, FileCheck2, FileText } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type Dashboard = { supplier: { name: string; portal_status: string; documents: { id: number; status: string; expires_at: string | null }[] }; profile_completion: number; response_counts: Record<string, number>; expiring_document_count: number };
export function SupplierDashboard() { const [data, setData] = useState<Dashboard | null>(null); useEffect(() => { void api<{ data: Dashboard }>("supplier-portal/dashboard").then((result) => setData(result.data)); }, []); if (!data) return <LoadingState label="Loading dashboard" />; const expiring = data.expiring_document_count; return <div className="supplier-page"><header className="supplier-page-heading"><div><span className="eyebrow">Supplier workspace</span><h1>Welcome, {data.supplier.name}</h1><p>Keep your company compliant and respond to matching procurement opportunities.</p></div><StatusBadge status={data.supplier.portal_status} /></header><div className="supplier-kpis"><article><CheckCircle2 /><div><span>Profile completion</span><strong>{data.profile_completion}%</strong></div></article><article><FileCheck2 /><div><span>Uploaded documents</span><strong>{data.supplier.documents.length}</strong></div></article><article><FileText /><div><span>Submitted responses</span><strong>{data.response_counts.submitted ?? 0}</strong></div></article><article className={expiring ? "warn" : ""}><AlertTriangle /><div><span>Documents expiring</span><strong>{expiring}</strong></div></article></div><section className="supplier-panel"><div className="panel-heading"><div><h2>Next actions</h2><p>Complete these items to remain eligible.</p></div></div>{data.profile_completion < 100 || data.supplier.documents.length === 0 ? <div className="action-list">{data.profile_completion < 100 && <Link href="/profile"><UserAction title="Complete company profile" copy="Add all required company and category information." /></Link>}{data.supplier.documents.length === 0 && <Link href="/documents"><UserAction title="Upload compliance documents" copy="Add registration, tax and business licence documents." /></Link>}</div> : <EmptyState title="You are up to date" copy="No supplier actions require attention." />}</section></div>; }
function UserAction({ title, copy }: { title: string; copy: string }) { return <><span><strong>{title}</strong><small>{copy}</small></span><b>Continue →</b></>; }
