"use client";

import { EmptyState, LoadingState, StatusBadge } from "@/components/ui/portal-ui";
import { api, collectionFrom } from "@/lib/api";
import { formatDate, statusLabel } from "@/lib/formatters";
import { FileUp, LoaderCircle } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Document = { id: number; document_type: string; document_number: string | null; original_name: string; original_filename: string | null; status: string; verification_status: string; verification_notes: string | null; issue_date: string | null; expiry_date: string | null; created_at: string };
const documentTypes = ["certificate_of_incorporation_or_business_registration", "brela_compliance_document", "business_license", "tin_certificate", "vat_certificate", "tax_clearance_certificate", "proof_of_physical_office", "director_or_owner_identification", "bank_confirmation", "product_catalogue", "manufacturer_authorisation", "quality_certificate", "tmda_or_regulatory_license", "import_or_wholesale_permit", "contract", "other"];

export function SupplierDocuments() {
  const [docs, setDocs] = useState<Document[] | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(() => api("supplier-portal/documents").then((value) => setDocs(collectionFrom(value).rows as Document[])), []);
  useEffect(() => { void load(); }, [load]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try { await api("supplier-portal/documents", { method: "POST", body: form }); setMessage("Document uploaded for verification."); event.currentTarget.reset(); await load(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Upload failed."); } finally { setBusy(false); } }
  return <div className="supplier-page"><header className="supplier-page-heading"><div><span className="eyebrow">Compliance evidence</span><h1>Company documents</h1><p>Expiry dates are monitored at 30, 60, and 90 days. Bank confirmation remains Finance/Admin only.</p></div></header><section className="supplier-panel"><h2>Upload a document</h2><form className="document-upload supplier-document-upload" onSubmit={upload}><label className="portal-field"><span>Document type</span><select name="document_type" required>{documentTypes.map((type) => <option value={type} key={type}>{statusLabel(type)}</option>)}</select></label><label className="portal-field"><span>Document number</span><input name="document_number" /></label><label className="portal-field"><span>Issue date</span><input type="date" name="issue_date" /></label><label className="portal-field"><span>Expiry date</span><input type="date" name="expiry_date" /></label><label className="file-drop"><FileUp /><span><strong>Select PDF or image</strong><small>Maximum 10 MB</small></span><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png" required /></label><button className="portal-button primary" disabled={busy}>{busy && <LoaderCircle className="spin" size={17} />}Upload securely</button></form>{message && <div className="portal-alert">{message}</div>}</section><section className="supplier-panel"><div className="panel-heading"><h2>Uploaded documents</h2></div>{docs === null ? <LoadingState /> : docs.length === 0 ? <EmptyState title="No documents uploaded" copy="Upload the mandatory registration, licence, tax, and category documents." /> : <div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Document</th><th>Type / number</th><th>Issued</th><th>Expiry</th><th>Status</th><th>Review note</th></tr></thead><tbody>{docs.map((doc) => <tr key={doc.id}><td><a href={`/backend/supplier-portal/documents/${doc.id}/download`}>{doc.original_filename ?? doc.original_name}</a></td><td>{statusLabel(doc.document_type)}<small>{doc.document_number ?? "No number"}</small></td><td>{formatDate(doc.issue_date)}</td><td>{formatDate(doc.expiry_date)}</td><td><StatusBadge status={doc.verification_status ?? doc.status} /></td><td>{doc.verification_notes ?? "—"}</td></tr>)}</tbody></table></div>}</section></div>;
}
