"use client";

import { useAuth } from "@/components/auth-provider";
import { FieldError } from "@/components/ui/portal-ui";
import { api, ApiError } from "@/lib/api";
import type { Category } from "@/lib/portal-types";
import { Building2, Check, ChevronLeft, ChevronRight, LoaderCircle, ShieldCheck, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";

type Values = Record<string, string | boolean | number[]>;
const initial: Values = {
  email: "", password: "", password_confirmation: "", legal_name: "", trading_name: "", supplier_type: "limited_company", registration_number: "", brela_registration_number: "", incorporation_or_compliance_number: "", business_license_number: "", business_license_issuing_authority: "", business_license_expiry_date: "", tin_number: "", vat_registered: false, vat_registration_number: "", tax_clearance_number: "", tax_clearance_expiry_date: "", physical_office_address: "", building_plot_street: "", ward: "", district: "", region: "", country: "Tanzania", postal_address: "", website: "", primary_contact_name: "", primary_contact_position: "", primary_contact_phone: "", primary_contact_email: "", alternate_contact_name: "", alternate_contact_phone: "", category_ids: [], products_services: "", manufacturer_or_distributor_status: "", years_in_operation: "", delivery_coverage_areas: "", quality_management_notes: "", regulated_supplier: false, declaration_accurate: false, agree_terms: false, agree_privacy: false,
};
const supplierTypes = ["limited_company", "business_name", "partnership", "sole_proprietor", "ngo", "government_entity", "other"];

export function SupplierRegistrationForm() {
  const { refresh } = useAuth();
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [values, setValues] = useState<Values>(initial);
  const [categories, setCategories] = useState<Category[]>([]);
  const [errors, setErrors] = useState<Record<string, string[]>>({});
  const [submitting, setSubmitting] = useState(false);
  useEffect(() => { void api<{ data: Category[] }>("portal/supplier-categories").then((data) => setCategories(data.data)); }, []);
  const set = (name: string, value: string | boolean | number[]) => setValues((current) => ({ ...current, [name]: value }));
  const input = (name: string, label: string, type = "text", required = false) => <label className="portal-field"><span>{label}{required && " *"}</span><input type={type} value={String(values[name])} onChange={(event) => set(name, event.target.value)} required={required} /><FieldError message={errors[name]?.[0]} /></label>;
  function toggleCategory(id: number) { const ids = values.category_ids as number[]; set("category_ids", ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]); }
  async function submit(event: FormEvent) { event.preventDefault(); if (step < 5) { setStep((current) => current + 1); return; } setSubmitting(true); setErrors({}); try { await api("portal/supplier-registration", { method: "POST", body: JSON.stringify(values) }); await refresh(); router.replace("/supplier-dashboard"); } catch (caught) { if (caught instanceof ApiError) setErrors(caught.errors ?? { form: [caught.message] }); } finally { setSubmitting(false); } }
  return <div className="registration-shell"><ol className="stepper">{([[1, "Account"], [2, "Business"], [3, "Tax & licence"], [4, "Contact & capability"], [5, "Declaration"]] as const).map(([number, label]) => <li className={step >= number ? "active" : ""} key={number}><span>{step > number ? <Check size={15} /> : number}</span><strong>{label}</strong></li>)}</ol>
    <form className="registration-form" onSubmit={submit}><header><span className="eyebrow">Step {step} of 5</span><h1>{["Create your supplier account", "Business identity", "Tax and licence details", "Contacts and capability", "Review and declare"][step - 1]}</h1><p>Use details that match the supporting compliance documents.</p></header>{errors.form && <div className="portal-alert error">{errors.form[0]}</div>}
      {step === 1 && <div className="portal-form-grid"><div className="form-callout"><UserRound size={22} /><p>Use a company-controlled email address. This becomes the supplier portal login.</p></div>{input("email", "Account email", "email", true)}{input("password", "Password", "password", true)}{input("password_confirmation", "Confirm password", "password", true)}</div>}
      {step === 2 && <div className="portal-form-grid two"><div className="form-callout full"><Building2 size={22} /><p>Enter the legal identity exactly as registered in Tanzania.</p></div>{input("legal_name", "Legal name", "text", true)}{input("trading_name", "Trading name")}<label className="portal-field"><span>Supplier type *</span><select value={String(values.supplier_type)} onChange={(event) => set("supplier_type", event.target.value)}>{supplierTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label>{input("registration_number", "Registration number")}{input("brela_registration_number", "BRELA registration number")}{input("incorporation_or_compliance_number", "Incorporation/compliance number")}<label className="portal-field full"><span>Physical office address *</span><textarea value={String(values.physical_office_address)} onChange={(event) => set("physical_office_address", event.target.value)} required /></label>{input("building_plot_street", "Building, plot or street")}{input("ward", "Ward")}{input("district", "District")}{input("region", "Region", "text", true)}{input("country", "Country", "text", true)}{input("postal_address", "Postal address")}{input("website", "Website", "url")}</div>}
      {step === 3 && <div className="portal-form-grid two"><div className="form-callout full"><ShieldCheck size={22} /><p>Expiry dates drive compliance alerts and award eligibility.</p></div>{input("tin_number", "TIN number", "text", true)}<label className="declaration-check"><input type="checkbox" checked={Boolean(values.vat_registered)} onChange={(event) => set("vat_registered", event.target.checked)} /><span>VAT registered</span></label>{Boolean(values.vat_registered) && input("vat_registration_number", "VAT registration number", "text", true)}{input("business_license_number", "Business licence number")}{input("business_license_issuing_authority", "Issuing authority")}{input("business_license_expiry_date", "Business licence expiry", "date")}{input("tax_clearance_number", "Tax clearance number")}{input("tax_clearance_expiry_date", "Tax clearance expiry", "date")}</div>}
      {step === 4 && <div className="portal-form-grid two">{input("primary_contact_name", "Primary contact name", "text", true)}{input("primary_contact_position", "Position")}{input("primary_contact_phone", "Phone", "tel", true)}{input("primary_contact_email", "Contact email", "email", true)}{input("alternate_contact_name", "Alternate contact")}{input("alternate_contact_phone", "Alternate phone", "tel")}<fieldset className="category-picker full"><legend>Supplier categories *</legend>{categories.map((category) => <label key={category.id}><input type="checkbox" checked={(values.category_ids as number[]).includes(category.id)} onChange={() => toggleCategory(category.id)} /><span>{category.name}</span></label>)}<FieldError message={errors.category_ids?.[0]} /></fieldset><label className="portal-field full"><span>Products and services *</span><textarea value={String(values.products_services)} onChange={(event) => set("products_services", event.target.value)} required /></label>{input("manufacturer_or_distributor_status", "Manufacturer/distributor status")}{input("years_in_operation", "Years in operation", "number")}<label className="portal-field full"><span>Delivery coverage areas</span><textarea value={String(values.delivery_coverage_areas)} onChange={(event) => set("delivery_coverage_areas", event.target.value)} /></label><label className="portal-field full"><span>Quality management notes</span><textarea value={String(values.quality_management_notes)} onChange={(event) => set("quality_management_notes", event.target.value)} /></label><label className="declaration-check full"><input type="checkbox" checked={Boolean(values.regulated_supplier)} onChange={(event) => set("regulated_supplier", event.target.checked)} /><span>We supply regulated goods or services and will provide applicable licences.</span></label></div>}
      {step === 5 && <div className="declaration"><div className="application-summary"><h2>{String(values.legal_name)}</h2><p>{String(values.primary_contact_email)} · {String(values.region)}, {String(values.country)}</p><span>{(values.category_ids as number[]).length} supplier categor{(values.category_ids as number[]).length === 1 ? "y" : "ies"}</span></div>{[["declaration_accurate", "I confirm that the submitted information is complete and accurate."], ["agree_terms", "I agree to the procurement portal terms and conditions."], ["agree_privacy", "I agree to the privacy notice and authorised document review."]].map(([name, label]) => <label className="declaration-check" key={name}><input type="checkbox" checked={Boolean(values[name])} onChange={(event) => set(name, event.target.checked)} required /><span>{label}</span></label>)}</div>}
      <footer><button type="button" className="portal-button secondary" disabled={step === 1 || submitting} onClick={() => setStep((current) => current - 1)}><ChevronLeft size={17} />Back</button><button className="portal-button primary" disabled={submitting}>{submitting ? <LoaderCircle className="spin" size={17} /> : step < 5 ? <ChevronRight size={17} /> : <Check size={17} />}{submitting ? "Submitting" : step < 5 ? "Continue" : "Submit application"}</button></footer>
    </form></div>;
}
